# Makefile for mandelbrot area code
#
# Fortran compiler and options for GNU 
#
#FC=	gfortran -O3
FC=     ftn -O3
 
#
# Object files
#
OBJ=	area.ser.o

#
# Compile
#
.SUFFIXES:	.f90 .o
area.ser:	$(OBJ)
	$(FC) -o $@ $(OBJ) 

.f90.o:
	$(FC) -c $< 

#
# Clean out object files and the executable.
#
clean:
	rm *.o area.ser
