# Makefile for mandelbrot area code

CC=     cc -O3 -acc -ta=nvidia -Minfo=accel
#LIB=	-lm

#
# Object files
#
OBJ=    area.acc.o

#
# Compile
#
area.acc:   $(OBJ)
	$(CC) -o $@ $(OBJ) $(LIB)

.c.o:
	$(CC) -c $<

#
# Clean out object files and the executable.
#
clean:
	rm -fr *.o area

